{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 123", "trace": "@allure.feature('模块二')\n    @allure.story('这是一个很牛逼的测试用例')\n    def test_3():\n>       assert 0 > 123\nE       assert 0 > 123\n\ntest_1.py:19: AssertionError"}, "start": 1566180560420, "stop": 1566180560421, "uuid": "694385b4-2383-4c57-ba15-327f462ae2bb", "historyId": "5573ca69ec5a612ab6ebd2e4e95d945e", "fullName": "test_1#test_3", "labels": [{"name": "feature", "value": "模块二"}, {"name": "story", "value": "这是一个很牛逼的测试用例"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-42BJSSG"}, {"name": "thread", "value": "5236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}